portal/forum/urls.py
from django.urls import path
from forum.views import *

urlpatterns = [
    path('', Forum_Themes_View.as_view(), name = "themes_list"),
    path('<int:pk>/', Posts_View.as_view(), name = "posts_list"),
    path('posts/<int:pk>/', Post_Detail_View.as_view(), name = "post_detail"),
    path('task_add/', PostAddView.as_view(), name="post_add"),
    path('<int:pk>/update/', PostUpdateView.as_view(), name = "post_update"),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name = "post_delete"),
    path('comment_add/', CommentAddView.as_view(), name="comment_add"),
    path('comment/<int:comment_id>/like-toggle/', CommentLikeToggle.as_view(), name='comment-like-toggle'),
    path('theme_add/', ThemeAddView.as_view(), name = "theme_add"),
    path('theme/<int:pk>/update/', ThemeUpdateView.as_view(), name = "theme_update")
    

]

app_name = "forum"

portal/portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from authentication.views import base_view, login_view, logout_view, register_view, profile_view, edit_profile_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name="main.html"), name="main_page"),

    # Register --- Login --- Logout #
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    #--- Profile ---#
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', edit_profile_view, name='edit_profile'),

    #--- Events ---#
    path('event/', include('event.urls')),

    # Voting polls #
    path('polls/', include('voting.urls')),

    # Forum #
    path('forum/', include('forum.urls'))
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from authentication.views import base_view, login_view, logout_view, register_view, profile_view, edit_profile_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name="main.html"), name="main_page"),

    # Register --- Login --- Logout #
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    #--- Profile ---#
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', edit_profile_view, name='edit_profile'),

    #--- Events ---#
    path('event/', include('event.urls')),

    # Voting polls #
    path('polls/', include('voting.urls')),

    # Forum #
    path('', include('forum.urls'))
]

portal/forum/models.py
from django.db import models
from django.contrib.auth.models import User


class Forum_Theme(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return f"{self.name}"

class Forum_post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    #media
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
    theme = models.ForeignKey(Forum_Theme, on_delete=models.CASCADE, related_name='themes')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"


class Comment(models.Model):
    post = models.ForeignKey(Forum_post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    #media = models.FileField(upload_to='comments_media/',blank = True, null =True)

    def get_absolute_url(self):
        return self.post.get_absolute_url()

class Like(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='liked_comments')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('comment', 'user')

portal/forum/forms.py
from django import forms
from forum.models import Forum_post, Comment, Forum_Theme

class PostAdd(forms.ModelForm):
    class Meta:
        model = Forum_post
        fields = ["title", "content", "theme"]

        widgets = {
            'theme': forms.HiddenInput()
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]

class ThemeAdd(forms.ModelForm):
    class Meta:
        model = Forum_Theme
        fields = ["name", "description"]

portal/forum/views.py
from django.shortcuts import render, redirect, get_object_or_404
from forum.models import *
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, View
from forum.forms import PostAdd, CommentForm, ThemeAdd
from django.contrib.auth.mixins import LoginRequiredMixin
from forum.mixins import *
from django.core.paginator import Paginator
from django.urls import reverse_lazy


class Forum_Themes_View(ListView):
    model = Forum_Theme
    context_object_name = "themes"
    template_name = "forum/themes_list.html"
    paginate_by = 7
    

class Posts_View(LoginRequiredMixin, ListView):
    model = Forum_post
    template_name = "forum/posts_list.html"
    context_object_name = "post"
    paginate_by = 6
    
    def get_queryset(self):
        theme_pk = self.kwargs.get('pk')
        theme = get_object_or_404(Forum_Theme, pk=theme_pk)
        posts = Forum_post.objects.filter(theme=theme)
        return posts

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['theme'] = get_object_or_404(Forum_Theme, pk=self.kwargs.get('pk'))
        return context

class Post_Detail_View(LoginRequiredMixin, DetailView):
    model = Forum_post
    template_name = "forum/post_detail.html"
    context_object_name = "post"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = CommentForm()  
        return context

    def post(self, request, *args, **kwargs):
        comment_form = CommentForm(request.POST, request.FILES)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.post = self.get_object()
            comment.save()
            return redirect('forum:post_detail', pk=comment.post.pk)

class CommentLikeToggle(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        comment_id = kwargs.get('comment_id')
        comment = Comment.objects.get(pk=comment_id)
        user = request.user
        like, created = Like.objects.get_or_create(comment=comment, user=user)
        if not created:
           
            like.delete()

       
        return redirect('forum:post_detail', pk=comment.post.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ["comments"] = Comment.objects.filter(post=self.get_object())
        return context

class ThemeAddView(LoginRequiredMixin, CreateView):
    model = Forum_Theme
    template_name = "forum/theme_add.html"
    form_class = ThemeAdd
    success_url = reverse_lazy("forum:themes_list")

class ThemeUpdateView(LoginRequiredMixin, UpdateView):
    model = Forum_Theme
    template_name = "forum/theme_update.html"
    form_class = ThemeAdd
    success_url = reverse_lazy("forum:themes_list")

class PostAddView(LoginRequiredMixin, CreateView):
    model = Forum_post
    template_name = "forum/post_add.html"
    form_class = PostAdd
    success_url = reverse_lazy("forum:themes_list")

    def get_initial(self):
        initial = super().get_initial()
        theme_pk = self.request.GET.get('theme')
        initial['theme'] = get_object_or_404(Forum_Theme, pk=theme_pk)
        return initial

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('forum:posts_list', kwargs={'pk': self.object.theme.pk})

class PostUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Forum_post
    template_name = "forum/post_update.html"
    form_class = PostAdd
    success_url = reverse_lazy("forum:themes_list")

class PostDeleteView(LoginRequiredMixin, UserIsOwnerMixin, DeleteView):
    model = Forum_post
    template_name = "forum/post_delete.html"
    success_url = reverse_lazy("forum:themes_list")

class CommentAddView(LoginRequiredMixin, CreateView):
    model = Comment
    template_name = "forum/comment_add.html"
    form_class = CommentForm
    success_url = reverse_lazy("forum:themes_list")

portal/templates/forum/post_add.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Создать новый пост</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Создать</button>
    </form>
</div>
{% endblock %}

portal/templates/forum/post_detail.html
{% extends "base.html" %}
{% load static %}

    {% block content %}
    <div class="row main-content mb-5" style="border: 2px solid;">
        <div class="col">
        <h4>{{ post.author }}</h4>
        <h1>{{ post.title }}</h1>
        <h2>{{ post.content }}</h2>
        </div>
    </div>


    
    <div class="comments">
        <h2>Сообщения:</h2>
        {% for comment in post.comments.all %}
            <div class="comment" style="border: 1px solid;">
                <small>{{ comment.author.username }}</small> <small>{{ comment.created_at }}</small>
                <p>{{ comment.content }}</p>
                <form action="{% url 'forum:comment-like-toggle' comment.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" name="like_button" class="btn btn-sm {% if request.user in comment.likes.all %}btn-success{% else %}btn-outline-secondary{% endif %}">
                        лайк {{ comment.likes.count }}
                    </button>
                </form>
            </div>
        {% empty %}
            <p>Комментариев нет.</p>
        {% endfor %}
    </div>

    <div class="add-comment mt-4">
        <h4>Ответить</h4>
        <form action="{% url 'forum:post_detail' post.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>
    
    {% endblock %}

portal/templates/forum/post_update.html
{% extends "base.html" %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <form>
            
      
            <button type="submit" class="btn btn-primary">Изменить пост</button>
          </form>
    </form>
{% endblock %}

portal/templates/forum/posts_list.html
{% extends "base.html" %}
    
    
    {% block content %}
    <div class="row main-content">
        <div class="col">
            <h1>Посты на тему: {{ theme.name }}</h1>
            <a href="{% url 'forum:post_add' %}?theme={{ theme.pk }}"><h3>Создать новый пост</h3></a>
            {% for post in post %}
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                      <a href="{% url 'forum:post_detail' post.pk %}"><h5 class="card-title">{{ post.title }}</h5></a>
                      <small-text class="card-subtitle mb-2 text-body-secondary">{{ post.author }}</small-text>
                      <small-text class="card-subtitle mb-2 text-body-secondary">{{ post.created_at }}</small-text>
                      <a href="{% url 'forum:post_update' post.pk %}"><h6 class="card-subtitle mb-2 text-body-secondary">Изменить пост</h6></a>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.number|add:-1 }}">Previous</a>

            </li>
            {% endif %}
            {% for page_num in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == page_num %}active {% endif %}"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"> 
                <a class="page-link" href="?page={{ page_obj.number|add:1 }}">Next</a>
            </li>
            {% endif %}

                </ul>
            </nav>           

        </div>
    </div>
    {% endblock %}

portal/templates/forum/theme_add.html
{% extends "base.html" %}


{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <form>
        
  
        <button type="submit" class="btn btn-primary">Создать тему</button>
      </form>
</form>
{% endblock %}

portal/templates/forum/theme_update.html
{% extends "base.html" %}


{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <form>
            
      
            <button type="submit" class="btn btn-primary">Изменить тему</button>
          </form>
    </form>
{% endblock %}

portal/templates/forum/themes_list.html
{% extends "base.html" %}
{% load static %}


    {% block content %}
    <div class="row mb-3">
        <div class="col">
            <h1>Темы форума</h1>
        </div>
    </div>
    <div class="col mb-5">
        {% for theme in themes %}
        <div class ="col-12  col-sm-6 col-md-4 col-lg-3">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <a href="{% url 'forum:posts_list' theme.pk %}"><h5 class="card-title">{{ theme.name }}</h5></a>
                  <h6 class="card-subtitle mb-1 text-body-secondary">{{ theme.description }}</h6>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-12">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.number|add:-1 }}">Previous</a>
            </li>
            {% endif %}
            {% for page_num in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == page_num %}active {% endif %}"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item"> 
                <a class="page-link" href="?page={{ page_obj.number|add:1 }}">Next</a>
            </li>
            {% endif %}
                </ul>
            </nav>           
        </div>
    </div>
    {% endblock %}
    </div>