portal/forum/urls.py
from django.urls import path
from forum.views import *

urlpatterns = [
    path('', Forum_Themes_View.as_view(), name = "themes_list"),
    path('<int:pk>/', Posts_View.as_view(), name = "posts_list"),
    path('posts/<int:pk>/', Post_Detail_View.as_view(), name = "post_detail"),
    path('task_add/', PostAddView.as_view(), name="post_add"),
    path('<int:pk>/update/', PostUpdateView.as_view(), name = "post_update"),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name = "post_delete"),
    path('comment_add/', CommentAddView.as_view(), name="comment_add"),
    path('comment/<int:comment_id>/like-toggle/', CommentLikeToggle.as_view(), name='comment-like-toggle'),
    path('theme_add/', ThemeAddView.as_view(), name = "theme_add"),
    path('theme/<int:pk>/update/', ThemeUpdateView.as_view(), name = "theme_update")
    

]

app_name = "forum"

portal/portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from authentication.views import base_view, login_view, logout_view, register_view, profile_view, edit_profile_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name="main.html"), name="main_page"),

    # Register --- Login --- Logout #
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    #--- Profile ---#
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', edit_profile_view, name='edit_profile'),

    #--- Events ---#
    path('event/', include('event.urls')),

    # Voting polls #
    path('polls/', include('voting.urls')),

    # Forum #
    path('forum/', include('forum.urls'))
]

portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from authentication.views import base_view, login_view, logout_view, register_view, profile_view, edit_profile_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name="main.html"), name="main_page"),

    # Register --- Login --- Logout #
    path('register/', register_view, name='register'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),

    #--- Profile ---#
    path('profile/', profile_view, name='profile'),
    path('profile/edit/', edit_profile_view, name='edit_profile'),

    #--- Events ---#
    path('event/', include('event.urls')),

    # Voting polls #
    path('polls/', include('voting.urls')),

    # Forum #
    path('', include('forum.urls'))
]

portal/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    
    <!-- Font - Marck Script -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Marck+Script&display=swap" rel="stylesheet">    
    <!-- Font - Cormorant Infant -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Infant:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Marck+Script&display=swap" rel="stylesheet">

    {% block additional_css %} {% endblock additional_css %}

    <title>{% block title %}Base{% endblock title %}</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<main class="container row">
{% include "navbar.html" %}
<div class="col">
{% block content %}

{% endblock content %}
</div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="{% static 'js/authentication.js' %}"></script>
</body>
</html>

portal/templates/edit_profile.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/edit_profile.css' %}">
{% block title %}Edit Profile{% endblock title %}
{% block content %}
    <h1>Edit Profile</h1>
    <form method="post" action="{% url 'edit_profile' %}">
        {% csrf_token %}
        <label for="id_username" class="form-label">Username:</label>
        <input type="text" class="form-control" name="username" id="id_username" value="{{ user.username }}" required><br>

        <label for="id_first_name" class="form-label">First Name:</label>
        <input type="text" class="form-control" name="first_name" id="id_first_name" value="{{ user.first_name }}"><br>

        <label for="id_last_name" class="form-label">Last Name:</label>
        <input type="text" class="form-control" name="last_name" id="id_last_name" value="{{ user.last_name }}"><br>

        <label for="id_email" class="form-label">Email:</label>
        <input type="email" class="form-control" name="email" id="id_email" value="{{ user.email }}" required><br>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </form>
{% endblock content %}

portal/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}Login Form{% endblock title %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% block content %}
    <div class="popup-form" id="popupForm">
        <h2>Login</h2>
        <form action="{% url 'login' %}" method="post">
            {% csrf_token %}
            
            <!-- Вивід повідомлення про помилку, якщо таке є -->            
            {% if error_message %}
            <div class="error-message">
                {{ error_message }}
            </div>
            {% endif %}

            <div>
                <label for="id_username" class="form-label">Username:</label>
                <input type="text" name="username" id="id_username" class="form-control" required>
            </div>
            <div>
                <label for="id_password" class="form-label">Password:</label>
                <input type="password" name="password" id="id_password" class="form-control" required>
            </div>
            <div>
                <button type="submit" class="btn btn-primary mt-2">Login</button>
            </div>
        </form>
    </div>
{% endblock content %}

portal/templates/main.html
{% extends "base.html" %}
{% block title %}Портал групи{% endblock title %}

{% block content %}
<h1 class="marck-script">Портал</h1>
<h2 class="marck-script">Опис сайту</h2>
<p class="cormorant-infant">Вітаємо на сайті нашої групи! Як учень ви можете завітати на наш форум, подивитися події, проголосувати, побачити новини та інше.</p>
<p class="cormorant-infant">Приклад інформації про нашу групу:</p>
<p class="cormorant-infant">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi eu luctus magna. Nunc facilisis orci ut ipsum hendrerit gravida. Sed ut magna et magna placerat porttitor in in nunc. Duis rhoncus ultricies mauris id accumsan. Proin egestas vel nibh non molestie. Sed gravida eros quam, in pellentesque risus lacinia sit amet. Cras mi mauris, posuere sed sollicitudin vel, gravida quis sapien. Aliquam ac leo nec nisl pretium bibendum. Morbi felis urna, posuere quis mauris eu, blandit egestas erat. Proin sit amet purus convallis, fermentum ante ut, varius justo. </p>
<h2 class="marck-script">Події скоро:</h2>
<ul class="cormorant-infant">
    <li>Деяка подія</li>
    <li>Інша подія</li>
    <li>Новіша подія</li>
</ul>
<h2 class="marck-script">Портфоліо учнів:</h2>
<ul class="cormorant-infant">
    <li>Портфоліо 1</li>
    <li>Портфоліо 2</li>
    <li>Портфоліо 3</li>
</ul>
<h2 class="marck-script">Сьогодні на форумі:</h2>
<ul class="cormorant-infant">
    <li><a href="/forum/1/">Пост 1</a></li>
    <li><a href="/forum/2/">Пост 2</a></li>
</ul>
{% endblock content %}

portal/templates/navbar.html
<div class="col-xs-12 col-sm-4 col-lg-2 mt-2">
<ul class="nav flex-sm-column nav-fill nav-tabs nav-stacked">
    <li class="nav-item">
        <a href={% url 'main_page' %} class="nav-link">Головна сторінка</a>
    </li>
    {% if user.is_authenticated %}
    <li class="nav-item">
        <a href={% url 'profile' %} class="nav-link">Мій профіль</a>
    </li>
    <li class="nav-item">
        <a href={% url 'logout' %} class="nav-link logout-btn">Вийти з акаунту</a>
    </li>
    {% else %}
    <li class="nav-item">
        <a href={% url 'register' %} class="nav-link" id="registerBtn">Зареєструватися</a>
    </li>
    <li class="nav-item">
        <a href={% url 'login' %} class="nav-link" id="loginBtn">Увійти в акаунт</a>
    </li>
    {% endif %}
    <li class="nav-item">
        <a href={% url 'event_list' %} class="nav-link">Події</a>
    </li>
    <li class="nav-item">
        <a href={% url 'voting_list' %} class="nav-link">Голосування</a>
    </li>
    <li class="nav-item">
        <a href={% url 'forum:themes_list' %} class="nav-link">Форум</a>
    </li>
</ul>
</div>

portal/templates/profile.html
{% extends "base.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% block title %}Profile{% endblock title %}
{% block content %}
    <h1>Profile of {{ user.username }}</h1>
    <p><strong>Username:</strong> {{ user.username }}</p>
    <p><strong>First name:</strong> {{ user.first_name }}</p>
    <p><strong>Last name:</strong> {{ user.last_name }}</p>
    <p><strong>Email:</strong> {{ user.email }}</p>
    <p><strong>Role:</strong> {{ user.role }}</p>
    <a href="{% url 'edit_profile' %}">Edit Profile</a>
{% endblock content %}

portal/templates/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}Registration Form{% endblock title %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% block content %}
    <div class="popup-form" id="registerPopupForm">
        <h2>Registration</h2>
        <form id="registerForm" action="{% url 'register' %}" method="post">
            {% csrf_token %}
            
            <!-- Вивід повідомлення про помилку, якщо таке є -->
            {% if error_message %}
            <div class="error-message">
                {{ error_message }}
            </div>
            {% endif %}

            <div>
                <label for="id_username" class="form-label">Username:</label>
                <input type="text" name="username" id="id_username" maxlength="150" class="form-control" required>
            </div>
            <div>
                <label for="id_email" class="form-label">Email:</label>
                <input type="email" name="email" id="id_email" class="form-control" required>
            </div>
            <div>
                <label for="id_first_name" class="form-label">First name:</label>
                <input type="text" name="first_name" class="form-control" id="id_first_name">
            </div>
            <div>
                <label for="id_last_name" class="form-label">Last name:</label>
                <input type="text" name="last_name" class="form-control" id="id_last_name">
            </div>
            <div>
                <label for="id_password1" class="form-label">Password:</label>
                <input type="password" name="password1" class="form-control" id="id_password1" required>
            </div>
            <div>
                <label for="id_password2" class="form-label">Password confirmation:</label>
                <input type="password" name="password2" class="form-control" id="id_password2" required>
            </div>
            <div>
                <button type="submit" class="btn btn-primary mt-2">Register</button>
            </div>
        </form>
    </div>
{% endblock content %}